server:
  port: 9192
spring:  h2:    console:      enabled: true  datasource:    url: jdbc:h2:mem:payment
  application:      name: PAYMENT-SERVICE
eureka:
  instance:
    prefer-ip-address: true  client:    service-url:      defaultZone: http://localhost:8762/eureka